TARGET_TITLES = [
    "junior applied ai engineer",
    "applied ai engineer",
    "ai automation engineer",
    "ai automation specialist",
    "junior ai automation specialist",
    "agentic ai engineer",
    "ai agents engineer",
    "ai agent engineer",
    "llm automation engineer",
    "llm engineer",
    "no-code automation engineer",
    "no-code ai automation specialist",
    "low-code automation engineer",
    "low-code ai automation specialist",
    "n8n automation specialist",
    "junior n8n specialist",
    "make.com automation engineer",
    "zapier automation specialist",
    "workflow automation engineer",
    "junior workflow automation specialist",
    "ai workflow specialist",
    "gtm engineer ai",
    "gtm automation engineer ai",
    "ai solutions engineer",
    "junior ai solutions specialist",
    "forward deployed ai engineer",
    "ai implementation specialist",
    "ai enablement specialist",
    "ai process automation specialist",
    "ai operations engineer",
    "business process automation specialist ai",
    "ai agents specialist",
    "junior ai agent engineer",
    "agentic systems engineer",
    "llm automation specialist",
    "mcp server developer",
    "mcp integration engineer",
    "ai tooling engineer",
    "revops automation specialist",
    "sales automation specialist ai",
    "operations automation specialist",
    "technical solutions engineer ai",
    "junior ki engineer",
    "ki automatisierung",
    "workflow automatisierung",
    "no-code automatisierung",
    "low-code automatisierung",
    "ki agenten",
    "ki lösungen",
    "werkstudent ki automatisierung",
    "praktikum ki automatisierung",
    "berufseinsteiger ki",
    "младший инженер ии",
    "начинающий инженер ии",
    "инженер по автоматизации ии",
    "специалист по автоматизации ии",
    "инженер llm",
    "инженер ai agents",
    "специалист n8n",
    "специалист make.com",
    "специалист zapier",
]

JUNIOR_SIGNALS = [
    "junior",
    "entry level",
    "entry-level",
    "internship",
    "intern",
    "associate",
    "graduate",
    "trainee",
    "working student",
    "early career",
    "new grad",
    "beginner",
    "0-1 years",
    "0-2 years",
    "1+ years",
    "2+ years",
    "werkstudent",
    "werkstudentin",
    "praktikum",
    "praktikant",
    "praktikantin",
    "berufseinsteiger",
    "berufseinsteigerin",
    "einstiegsposition",
    "absolvent",
    "absolventin",
    "0-1 jahre",
    "0-2 jahre",
    "1+ jahre",
    "2+ jahre",
    "младший",
    "начинающий",
    "стажер",
    "стажёр",
    "стажировка",
    "выпускник",
    "без опыта",
    "начальный уровень",
]

SENIOR_NEGATIVE_SIGNALS = [
    "senior",
    "staff",
    "principal",
    "lead",
    "manager",
    "director",
    "head of",
    "vp",
    "5+ years",
    "6+ years",
    "7+ years",
    "8+ years",
    "10+ years",
    "leiter",
    "leitung",
    "direktor",
    "teamlead",
    "teamleiter",
    "5+ jahre",
    "6+ jahre",
    "7+ jahre",
    "10+ jahre",
    "старший",
    "ведущий",
    "руководитель",
    "менеджер",
    "директор",
    "глава",
    "лид",
    "тимлид",
    "5+ лет",
    "6+ лет",
    "7+ лет",
    "10+ лет",
]

REMOTE_SIGNALS = [
    "fully remote",
    "remote-first",
    "remote friendly",
    "worldwide remote",
    "remote europe",
    "remote germany",
    "remote dach",
    "remote",
    "work from home",
    "distributed team",
    "homeoffice",
    "home-office",
    "fernarbeit",
    "ortsunabhängig",
    "deutschlandweit remote",
    "europaweit remote",
    "удаленно",
    "удалённо",
    "работа из дома",
    "дистанционно",
    "полностью удаленно",
    "полностью удалённо",
    "удаленная работа",
    "удалённая работа",
]

HYBRID_SIGNALS = ["hybrid", "partly remote", "teilweise remote", "гибрид"]

AUTOMATION_SKILLS = [
    "automation",
    "workflow automation",
    "mcp server",
    "model context protocol",
    "business process automation",
    "operations automation",
    "no-code",
    "low-code",
    "n8n",
    "make.com",
    "zapier",
    "airtable",
    "notion",
    "google sheets",
    "webhooks",
    "rest api",
    "integrations",
    "crm automation",
    "sales automation",
    "marketing automation",
    "gtm automation",
    "automatisierung",
    "автоматизация",
]

AI_SKILLS = [
    "ai",
    "artificial intelligence",
    "ki",
    "ии",
    "llm",
    "large language models",
    "gpt",
    "openai",
    "claude",
    "anthropic",
    "gemini",
    "mistral",
    "llama",
    "langchain",
    "langgraph",
    "mcp server",
    "model context protocol",
    "rag",
    "embeddings",
    "vector database",
    "prompt engineering",
    "ai agents",
    "agentic ai",
    "autonomous agents",
]

STARTUP_SIGNALS = ["startup", "early-stage", "early stage", "saas", "b2b", "gtm", "revops", "y combinator", "yc"]

QA_AUTOMATION_SIGNALS = ["qa automation", "test automation", "selenium", "cypress", "playwright testing"]

ROLE_TITLE_SIGNALS = [
    "engineer",
    "automation",
    "automatisierung",
    "workflow",
    "solutions",
    "solution",
    "implementation",
    "consultant",
    "specialist",
    "operations",
    "llm",
    "agent",
    "agents",
    "n8n",
    "make.com",
    "zapier",
    "no-code",
    "low-code",
    "ki-umsetzer",
    "ai enablement",
    "ai automation specialist",
    "ai workflow",
    "mcp server",
    "model context protocol",
    "ai tooling",
    "revops",
    "gtm",
]

UNRELATED_TITLE_SIGNALS = [
    "grafikdesigner",
    "graphic designer",
    "marketing coordinator",
    "customer support",
    "customer operations",
    "writing specialist",
    "kundensupport",
    "kundenbetreuung",
    "administrative support",
    "data entry",
    "robotics automation",
    "industrial automation",
    "plc automation",
    "factory automation",
    "building automation",
    "marketing automation manager",
]

# Roles that are clearly off-target even when the posting mentions AI (e.g. a
# "Web Developer" or "DevOps Engineer" at an AI company). These are penalized in
# the title unless the title is an explicit target role.
OFF_TARGET_TITLE_SIGNALS = [
    "web developer",
    "web development",
    "wordpress",
    "devops",
    "sre",
    "site reliability",
    "account executive",
    "account manager",
    "business development",
    "sales representative",
    "sales development",
    "graphic",
    "ux designer",
    "ui designer",
    "product designer",
    "recruiter",
    "talent acquisition",
    "billing",
    "bookkeeper",
    "accountant",
    "payroll",
    "customer service",
    "customer success",
    "customer support",
    "product support",
    "support specialist",
    "virtual assistant",
]

REGION_KEYWORDS = {
    "dach": [
        "germany",
        "deutschland",
        "austria",
        "österreich",
        "switzerland",
        "schweiz",
        "dach",
        "berlin",
        "munich",
        "münchen",
        "hamburg",
        "frankfurt",
        "cologne",
        "köln",
        "düsseldorf",
        "stuttgart",
        "vienna",
        "wien",
        "zurich",
        "zürich",
    ],
    "europe": [
        "europe",
        "europa",
        "eu",
        "netherlands",
        "amsterdam",
        "spain",
        "portugal",
        "france",
        "paris",
        "italy",
        "poland",
        "warsaw",
        "czech republic",
        "prague",
        "estonia",
        "lithuania",
        "latvia",
        "sweden",
        "finland",
        "denmark",
        "norway",
        "uk",
        "united kingdom",
        "london",
        "ireland",
        "dublin",
    ],
    "america": ["usa", "united states", "canada", "north america", "latin america", "south america", "mexico", "brazil", "argentina"],
    "asia": ["asia", "singapore", "india", "japan", "korea", "thailand", "vietnam", "philippines", "indonesia", "uae", "dubai"],
    "worldwide": ["worldwide", "global", "anywhere", "remote worldwide", "remote emea"],
}
